"""Initial migration

Revision ID: c74445d7deaa
Revises: 7de2327133aa
Create Date: 2024-12-03 20:44:42.356716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74445d7deaa'
down_revision = '7de2327133aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
